website/docs/glue-catalog.md, website/docs/hms.md, website/docs/unity-catalog.md
Removed `partitionSpec` wherever HUDI is not the sourceFormat
Removed `partitionSpec` wherever HUDI is not the sourceFormat
trivial
=> removed partitionSpec wherever Hudi is not the source

.github/workflows/site-deploy.yml
updates deployment to use key to bypass branch protection
- use key
=> Deploy pages with key

api/src/main/java/io/onetable/model/storage/OneDataFile.java, core/src/main/java/io/onetable/hudi/BaseFileUpdatesExtractor.java, core/src/main/java/io/onetable/hudi/HudiTargetClient.java, core/src/main/java/io/onetable/iceberg/IcebergDataFileExtractor.java, core/src/test/java/io/onetable/ITOneTableClient.java, core/src/test/java/io/onetable/iceberg/TestIcebergSourceClient.java, core/src/test/java/io/onetable/iceberg/TestIcebergSync.java
Addresses #207 
Fixes issues discovered in testing around path comparisons for local filesystem
- forces the paths to include a scheme
Covered by existing tests and expectations for Iceberg source tests were updated
=> Make data file path include scheme for consistency

website/README.md
Adding a note in website readme
Adding a note in website readme
trivial/tested on forked page
=> Website readme update

pom.xml
#213 Upgrade java dependencies with issues identified by dependabot
- update versions in pom
=> Dependabot: bump versions in pom

.github/workflows/package-deploy.yml
Improves existing release workflow after running it once
- update maven options
=> [minor] add no-transfer-progress and skip tests to release-packages workflow

core/src/test/java/io/onetable/ITOneTableClient.java, pom.xml
Fixes flakiness in test that has failed in CI a couple times today
- Adds sleep to ensure that time travel query is reading from correct second
- Update fork count for CI performance
=> [minor] fix issue in test flakiness

api/src/main/java/io/onetable/spi/extractor/SourceClient.java, core/src/main/java/io/onetable/client/OneTableClient.java, core/src/main/java/io/onetable/delta/DeltaSourceClient.java, core/src/main/java/io/onetable/hudi/HudiClient.java, core/src/main/java/io/onetable/iceberg/IcebergSourceClient.java
There are some items that should be closed in the source clients so we need to make the source client closeable and invoke the close during the sync process.
- Add closeable to the interface
- add implementations to all sources
=> Mark source client as closeable and prevent leaks

README.md
Added an example on how to provide path for ABFS.
- This PR adds an example to existing YAML on how to provide ABFS path as an input.
- Updated README.md
- This pull request is a trivial rework / code cleanup without any test coverage.
=> Update README.md to add example on how to provide ABFS path.

website/docs/athena.md, website/docs/features-and-limitations.md, website/docs/glue-catalog.md, website/docs/spark.md
Fixing docs to mention that the query engines require 0.14.0 version.
Fixing docs to mention that the query engines require 0.14.0 version.
tested locally
=> Doc updates from delta source tests

core/src/main/java/io/onetable/delta/DeltaTableExtractor.java, core/src/main/java/io/onetable/hudi/HudiTableManager.java, core/src/main/java/io/onetable/iceberg/IcebergSourceClient.java, core/src/test/java/io/onetable/GenericTable.java, core/src/test/java/io/onetable/ITOneTableClient.java, core/src/test/java/io/onetable/TestSparkDeltaTable.java, core/src/test/java/io/onetable/delta/ITDeltaSourceClient.java, core/src/test/java/io/onetable/hudi/TestHudiTableManager.java, core/src/test/java/io/onetable/iceberg/TestIcebergSourceClient.java
Add tests for testing partition filter behavior
1. Add tests for partition filters work for all formats.
2. Basic filters for Iceberg & Delta while more advanced filters for Hudi
=> Add partition filters Testing to all Formats

api/src/main/java/io/onetable/model/schema/OneSchema.java, core/src/main/java/io/onetable/avro/AvroSchemaConverter.java, core/src/main/java/io/onetable/collectors/CustomCollectors.java, core/src/main/java/io/onetable/delta/DeltaClient.java, core/src/main/java/io/onetable/delta/DeltaDataFileUpdatesExtractor.java, core/src/main/java/io/onetable/delta/DeltaPartitionExtractor.java, core/src/main/java/io/onetable/delta/DeltaSchemaExtractor.java, core/src/main/java/io/onetable/delta/DeltaStatsExtractor.java, core/src/main/java/io/onetable/hudi/BaseFileUpdatesExtractor.java, core/src/main/java/io/onetable/hudi/HudiClient.java, core/src/main/java/io/onetable/hudi/HudiDataFileExtractor.java, core/src/main/java/io/onetable/hudi/HudiFileStatsExtractor.java, core/src/main/java/io/onetable/iceberg/IcebergColumnStatsConverter.java, core/src/main/java/io/onetable/iceberg/IcebergSchemaExtractor.java, core/src/main/java/io/onetable/iceberg/IcebergSchemaSync.java
A further optimization as part of #148 around sizing of ArrayLists outputted from streams when the size is known
- Add custom collector with set array list size
- Update usage to this collector when there are potentially large lists and size is known
- Update some usage of streams to avoid multiple list creation
This is a refactor that does not impact the logic and will be covered by existing testing
=> Optimize stream to list collection 

core/src/main/java/io/onetable/delta/DeltaDataFileUpdatesExtractor.java, core/src/main/java/io/onetable/paths/PathUtils.java, core/src/test/java/io/onetable/paths/TestPathUtils.java
Addresses #230 by better handling small differences in scheme of files
- Create util for getting relative path
Added unit test
=> add path utils for fetching relative path and unit tests

demo/docker-compose.yaml, website/docs/how-to.md
Fix typos for Iceberg sourceFormat
Fix typos for Iceberg sourceFormat in how-to docs
Minor/trivial
=> Docs update quickstart iceberg

demo/README.md, website/docs/demo/docker.md
Add info about presto on docker demo docs and docker demo readme
changed readme for docker demo
added info on docker demo website docs
verified changes locally `npm run build` and `npm run serve`
=> add info about presto on docs

pom.xml
there are two `log4j-1.2-api` in `pom.xml`
- remove duplicated dependency
CI
=> remove duplicated dependency

website/README.md
added note for adding a new blog
added note for adding a new blog
trivial 
readme update
=> added note for adding blogs

website/docusaurus.config.js, website/static/index.html
Added blogs button to site home
UI change
Added Blog button on site home
Minor, visual
=> [DOCS][MINOR] Added blogs button in homepage

website/docs/starrocks.md, website/sidebars.js
adding in StarRocks connection information
documentation to the website
=> adding in StarRocks connection information

demo/notebook/demo.ipynb
Variable changed and missed to change in the whole demo: PerTableConfig -> PerTableConfigImpl
=> Update demo.ipynb - PerTableConfigImpl 

.github/dependabot.yml, .github/workflows/azure_ci_check.yml, .github/workflows/package-deploy.yml, .github/workflows/scheduled_workflow.yml, .github/workflows/site-build.yml, .github/workflows/site-deploy.yml
Update github actions to their latest versions and add dependabot for automatic updates. (Dependabot requires also to be enabled in the repository settings).
- *Update github actions to their latest versions*
- *Add dependabot configuration for automatic updates*
This pull request is already covered by existing tests.
=> Update github actions to their latest versions and add dependabot for automatic updates

api/src/main/java/org/apache/xtable/client/CatalogConfig.java, api/src/main/java/org/apache/xtable/model/OneSnapshot.java, api/src/main/java/org/apache/xtable/model/schema/PartitionTransformType.java
This PR fixes some typos in the API docstrings
=> Fix some typos in the api docstrings

core/pom.xml
=> Remove duplicate dependencies

pom.xml
Add spotless exclusion check folder
=> Add spotless exclusion check folder

website/docs/fabric.md
Fix wrong item number in fabric doc.
Fix wrong item number in fabric doc.
=> [Docs] Fix wrong item number in fabric doc

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/xtable_bug_report.yml, .github/ISSUE_TEMPLATE/xtable_improvement_feature.yml
Fixed #426
Add Issue template for xtable project.
e.g
- https://github.com/apache/doris/issues/new/choose
- https://github.com/apache/iceberg/issues/new/choose
- https://github.com/apache/hudi/issues/new/choose
- *Fixed JSON parsing error when persisting state*
- *Added unit tests for schema evolution*
=> [Infra] Add Issue template for xtable project

website/docs/biglake-metastore.md, website/docs/glue-catalog.md, website/docs/hms.md, website/docs/how-to.md, website/docs/unity-catalog.md
- minor
Fix missing xtable prefix to utilities-bundled.jar in docs.
As title.
Local.
=> [MINOR] Fix missing xtable prefix to utilities-bundled.jar in docs

demo/notebook/demo.ipynb
- hotfix.
Add xtable prefix to hudi-support jar in demo jupyter node.
Add xtable prefix to hudi-support jar in demo jupyter node.
Manually verified the change by running a job locally.
=> [hotfix] Add xtable prefix to hudi-support jar in demo jupyter node

website/docs/unity-catalog.md
https://github.com/apache/incubator-xtable/issues/470
- Doc update that includes steps to integrate with OSS UC
- Modified `unity-catalog.md`
- Doc update/trivial
=> [DOCS] adding changes related to oss unity catalog to the docs

DISCLAIMER-WIP, pom.xml
Adding DISCLAIMER-WIP as per apache guide mentioned below. 
https://incubator.apache.org/policy/incubation.html#disclaimers 
This was decided based on the feedback given by the community in this dev mail thread. 
https://lists.apache.org/thread/kjwtg55rdcllvyol6sqszd6ozgto7z45
- *Add DISCLAIMER-WIP*
=> [486] Add DISCLAIMER-WIP for first release

xtable-hudi-support/xtable-hudi-support-utils/src/main/java/org/apache/xtable/hudi/idtracking/models/IdTracking.java
hotfix
Fix typo in IdTracking.
Fix typo in IdTracking.
*(or)*
(or)
*(example:)*
- *Added TestConversionController to verify the change.*
=> Fix typo in IdTracking

README.md, xtable-api/src/main/java/org/apache/xtable/conversion/HudiSourceConfig.java
hotfix
Use this small issue to verify the github action.
https://issues.apache.org/jira/browse/INFRA-25953
=> Remove redundant modifier for interface members

Dockerfile, README.md
=> added docker file (#1)

README.md
There's no issue - I just noticed some typo and other formatting problems.
- fix typos some formatting
- One commit for fixing README
=> docs: fix typos and tidying

website/blog/aws-mwaa.mdx, website/blog/xtable-databricks.mdx, website/blog/xtable-iceberg-fs-catalog.mdx, website/blog/xtable-unity.mdx
- Add 4 new community blogs related to XTable from the community
- trivial change
=> Add 4 New Community Blogs to the Apache XTable Blogs section

website/README.md, website/docusaurus.config.js, website/releases/downloads.mdx, website/releases/release-0.1.0-incubating.mdx
https://github.com/apache/incubator-xtable/issues/519
1. Add Downloads navbar to the site
2. Add release file/links to the site under Downloads section
1. Added new dir/files related to release
2. Changed `docusaurus.config.js` to support navigation
Doc update
=> [DOCS] add releases page and modify README.md

website/README.md, website/static/index.html
1. Add release section to the site
2. Add new release to the releases section
=> [DOCS] added Downloads link to the site homepage

website/releases/downloads.mdx
ASF policy for download pages: https://infra.apache.org/release-download-pages.html
1. Remove links to dist.apache.org
2. Use closer.lua for source artifacts
3. Add link to the official KEYS file
4. Add link to instructions for verifying releases
Deployed the website locally and clicked on all links
=> Update Downloads page to adhere to the ASF policy

pom.xml
- This pull request aims to address issues #546 
*This pull request fixes the lombok jar dependency scope*
- *Updated pom file to fix the lombok dependency scope to provided*
=> [546] Update Lombok Dependency Scope in Project

pom.xml
relates to #558 
*(For example: This pull request implements the sync for delta format.)*
- *Fixed JSON parsing error when persisting state*
- *Added unit tests for schema evolution*
*(or)*
(or)
*(example:)*
- *Added TestConversionController to verify the change.*
=> use avro 1.11.4 due to CVE-2024-47561

README.md
Small PR
Commit d991e75339f2c564897828bf6d647fcccd986cc5 moved the location of `xtable-hadoop-defaults.xml`. This PR adjusts sources to changes.
- Update `xtable-hadoop-defaults.xml` reference
=> Update `xtable-hadoop-defaults.xml` reference

.github/workflows/site-deploy.yml, website/README.md, website/docusaurus.config.js, website/releases/downloads.mdx, website/releases/release-0.2.0-incubating.mdx, website/static/index.html
Add downloads page for 0.2.0-incubating release
- *Add downloads page for 0.2.0-incubating*
Verified the website docs reflect properly in local.
=> [551] Add downloads page for 0.2.0-incubating release

website/docs/snowflake.md
https://github.com/apache/incubator-xtable/issues/579
Docs update to remove info on snowflake public preview support for Iceberg
Doc update
Local testing
=> [DOCS] Remove info on snowflake public preview for Iceberg

xtable-api/src/main/java/org/apache/xtable/conversion/ExternalCatalog.java, xtable-api/src/main/java/org/apache/xtable/conversion/ExternalTable.java, xtable-api/src/main/java/org/apache/xtable/conversion/SourceCatalog.java, xtable-api/src/main/java/org/apache/xtable/conversion/SourceTable.java, xtable-api/src/main/java/org/apache/xtable/conversion/TargetTable.java, xtable-api/src/main/java/org/apache/xtable/model/sync/SyncResult.java, xtable-api/src/main/java/org/apache/xtable/spi/extractor/CatalogConversionSource.java, xtable-api/src/main/java/org/apache/xtable/spi/extractor/ConversionSource.java, xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSync.java, xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSyncClient.java, xtable-api/src/main/java/org/apache/xtable/spi/sync/TableFormatSync.java, xtable-api/src/test/java/org/apache/xtable/conversion/TestExternalTable.java, xtable-api/src/test/java/org/apache/xtable/spi/sync/TestExternalCatalogSync.java, xtable-api/src/test/java/org/apache/xtable/spi/sync/TestTableFormatSync.java, xtable-core/src/main/java/org/apache/xtable/catalog/CatalogConversionFactory.java, xtable-core/src/main/java/org/apache/xtable/catalog/ExternalCatalogConfig.java, xtable-core/src/main/java/org/apache/xtable/conversion/ConversionController.java, xtable-core/src/main/java/org/apache/xtable/delta/DeltaConversionSource.java, xtable-core/src/main/java/org/apache/xtable/hudi/HudiConversionSource.java, xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java, xtable-core/src/test/java/org/apache/xtable/conversion/TestConversionController.java, xtable-hudi-support/xtable-hudi-support-extensions/src/main/java/org/apache/xtable/hudi/sync/XTableSyncTool.java, xtable-utilities/src/main/java/org/apache/xtable/utilities/RunCatalogSync.java, xtable-utilities/src/main/java/org/apache/xtable/utilities/RunSync.java, xtable-utilities/src/main/resources/catalogConfig.yaml
*(For example: This pull request implements the sync for delta format.)*
- *Fixed JSON parsing error when persisting state*
- *Added unit tests for schema evolution*
*(or)*
(or)
*(example:)*
- *Added TestConversionController to verify the change.*
=> [590] Add syncCatalogs in ConversionController

pom.xml, xtable-core/src/test/java/org/apache/xtable/delta/ITDeltaConversionSource.java, xtable-core/src/test/java/org/apache/xtable/hudi/ITHudiConversionSource.java, xtable-core/src/test/java/org/apache/xtable/hudi/ITHudiConversionTarget.java, xtable-core/src/test/java/org/apache/xtable/hudi/TestHudiConversionTarget.java, xtable-core/src/test/java/org/apache/xtable/iceberg/ITIcebergConversionSource.java, xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergConversionSource.java
Addresses #619 
- Update test names that are incorrect
- Update dependencies used in the project 
=> [619] Maintenance: Update dependencies, fix test class names

website/community/community.md
- Updated the newly created Community page.
[x] This pull request is a trivial rework / code cleanup without any test coverage.
=> Updated the New Community Page

README.md
Small PR.
Commit d991e75339f2c564897828bf6d647fcccd986cc5 moved `ConversionTarget.java` and `ConversionController.java`. This PR adjusts sources to changes.
- Update  `ConversionTarget.java` and `ConversionController.java` in `README.md`.
=> Update xtable-api sources

xtable-api/src/main/java/org/apache/xtable/model/schema/InternalType.java, xtable-core/src/main/java/org/apache/xtable/conversion/ConversionController.java, xtable-core/src/main/java/org/apache/xtable/delta/DeltaPartitionExtractor.java, xtable-core/src/main/java/org/apache/xtable/hudi/HudiFileStatsExtractor.java
Fixes a few minor items flagged by our internal static analysis of the repo
- Cleanup reused code around stats in Hudi
- Inline set creation
- Use a regex for extracting delta partition details
Covered by existing tests
=> [MINOR] fixes recommended from static analysis tooling

Dockerfile
Fixes issue with multiline statement in Dockerfile
- Adds `\`
-  Built docker image locally
=> [MINOR] Fix docker file syntax issue

xtable-utilities/src/main/java/org/apache/xtable/utilities/RunCatalogSync.java, xtable-utilities/src/main/java/org/apache/xtable/utilities/RunSync.java, xtable-utilities/src/test/java/org/apache/xtable/utilities/TestRunSync.java, xtable-utilities/src/test/resources/my_config.yaml
* Refactor RunSync Class for Improved Modularity and Reusability *
Refactored the main method into smaller methods as per PR.
Added some positive and negative testcases
=> [528] Refactor RunSync Class for Improved Modularity and Reusability

.asf.yaml
- Adds required entry for discussions notifications
- Updates issues notifications to go to issues mailing list
- update asf.yaml notifications section
=> [MINOR] Add mailing list for discussions, update issues list in asf.yaml

.asf.yaml
Fixes mailing list used since issues list does not exist for this project
- Update mailing list
=> [MINOR] Fix mailing list in asf.yaml

NOTICE
The NOTICE files in the repo and inside the jars do not reflect the current year (2025).
- *The NOTICE files in the repo and inside the jars do not reflect the current year (2025).*
=> [692] Include 2025 in NOTICE file

xtable-aws/src/main/resources/META-INF/LICENSE-bundled, xtable-hive-metastore/src/main/resources/META-INF/LICENSE-bundled, xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/LICENSE-bundled
Addressing feedback from @zabetak and @jbonofre from rc2 vote thread. 
https://github.com/apache/incubator-xtable/issues/700 
- *Update license files for bundled jars*
=> [700] Update license files for bundled jars

xtable-aws/pom.xml, xtable-aws/src/main/resources/META-INF/NOTICE-bundled, xtable-hive-metastore/pom.xml, xtable-hive-metastore/src/main/resources/META-INF/LICENSE-bundled, xtable-hive-metastore/src/main/resources/META-INF/NOTICE-bundled, xtable-hudi-support/xtable-hudi-support-extensions/pom.xml, xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/NOTICE-bundled
Update NOTICE file based on consensus from this GH discussion. 
https://github.com/apache/incubator-xtable/pull/707#issuecomment-2856594883
- *Update NOTICE file for bundled jars*
=> [700] Update NOTICE file for bundled jars

xtable-api/src/main/java/org/apache/xtable/model/InternalTable.java, xtable-core/src/main/java/org/apache/xtable/delta/DeltaTableExtractor.java, xtable-core/src/main/java/org/apache/xtable/hudi/HudiTableExtractor.java, xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java, xtable-core/src/test/java/org/apache/xtable/delta/ITDeltaConversionSource.java, xtable-core/src/test/java/org/apache/xtable/hudi/ITHudiConversionSource.java, xtable-core/src/test/java/org/apache/xtable/testutil/ITTestUtils.java, xtable-service/src/main/java/org/apache/xtable/service/ConversionService.java, xtable-service/src/test/java/org/apache/xtable/service/TestConversionService.java
Fix typo in the InternalTable class
- *Fix typo in the InternalTable class*
=> Fix typo in InternalTable

website/releases/downloads.mdx, website/releases/release-0.2.0-incubating.mdx, website/releases/release-0.3.0-incubating.mdx
https://github.com/apache/incubator-xtable/issues/724
* Add a new 0.3.0 release page
- Add a new 0.3.0 release page
- Modify the Downloads page to include the new release
=> [DOCS] Add a new 0.3.0 release page
