apache/incubator-xtable

- core/src/main/java/io/onetable/delta/DeltaActionsConverter.java
- core/src/test/java/io/onetable/GenericTable.java
- core/src/test/java/io/onetable/ITOneTableClient.java
- core/src/test/java/io/onetable/TestAbstractHudiTable.java
- core/src/test/java/io/onetable/TestSparkDeltaTable.java
- core/src/test/java/io/onetable/delta/ITDeltaSourceClient.java
#102 highlights that we do not properly set the record count when Delta is the source. Until we upgrade, we can simply get the count from the column level stats for the file.
- Use column stats for count
- Added integration test that performs filter, this is how the regression was discovered
- Updates unit test check
> add a workaround until delta version is upgraded to include record count

- api/src/main/java/io/onetable/spi/sync/TableFormatSync.java
- core/src/main/java/io/onetable/client/OneTableClient.java
- core/src/test/java/io/onetable/client/TestOneTableClient.java
This is preparation for a larger change for #148 where we'll make the table changes return as an iterator to avoid loading all changes into memory at once.
- Leverages existing metadata to reduce number of maps maintained
- Ensures the target state is read once for efficiency 
> Refactor OneTableClient in preparation for iterative table changes fetching

- core/src/main/java/io/onetable/iceberg/IcebergSourceClient.java
- core/src/test/java/io/onetable/TestIcebergTable.java
- core/src/test/java/io/onetable/iceberg/ITIcebergSourceClient.java
Fallback to Full sync automatically when it is not safe for incremental sync.
1. In the presence of expired snapshots, detect and fall back to snapshot sync.
> Add check for iceberg when incremental sync is not safe

- api/src/main/java/io/onetable/model/IncrementalTableChanges.java
- api/src/main/java/io/onetable/model/sync/SyncResult.java
- api/src/main/java/io/onetable/spi/extractor/ExtractFromSource.java
- api/src/main/java/io/onetable/spi/sync/TableFormatSync.java
- api/src/main/java/io/onetable/spi/sync/TargetClient.java
- api/src/test/java/io/onetable/spi/extractor/TestExtractFromSource.java
- api/src/test/java/io/onetable/spi/sync/TestTableFormatSync.java
- core/src/main/java/io/onetable/client/OneTableClient.java
- core/src/main/java/io/onetable/client/TableFormatClientFactory.java
- core/src/main/java/io/onetable/delta/DeltaClient.java
- core/src/main/java/io/onetable/hudi/HudiTargetClient.java
- core/src/main/java/io/onetable/iceberg/IcebergClient.java
- core/src/test/java/io/onetable/ITOneTableClient.java
- core/src/test/java/io/onetable/client/TestOneTableClient.java
- core/src/test/java/io/onetable/delta/TestDeltaSync.java
- core/src/test/java/io/onetable/iceberg/TestIcebergSync.java
As part of #148  this change uses an iterator over the table changes instead of loading all of the changes into memory at once to reduce the memory overhear.
- Make TableChanges an iterator instead of a list
- Update TableFormatSync to be stateless and sync each target commit by commit instead of looping through all commits per target.
- Added additional unit tests for TableFormatSync around the logic for filtering which commits are synced per target client
- Updated existing tests around new expectations
> Use iterator over table changes during incremental sync

- utilities/src/main/java/io/onetable/utilities/RunSync.java
Fixes #254 
This is a minor enhancement in the `run sync` cli utility. Currently absence of required params does not produce useful error messages. With this change the help message will be printed. For e.g.
```
$ java -jar utilities/target/utilities-0.1.0-SNAPSHOT-bundled.jar                                
usage: onetable.jar [-c <arg>] -d <arg> [-h] [-i <arg>] [-p <arg>]
-c,--clientsConfig <arg>          The path to a yaml file containing
OneTable client configurations. These
configs will override the default
-d,--datasetConfig <arg>          The path to a yaml file containing
dataset configuration
-h,--help                         Displays help information to run this
utility
-i,--icebergCatalogConfig <arg>   The path to a yaml file containing
Iceberg catalog configuration. The …
```
> Improve sync utility cli parse error messages

- core/src/main/java/io/onetable/iceberg/IcebergSchemaExtractor.java
#261 
Usability improvement, if the record key field in hudi is not marked as required, do not try to set it as an iceberg identifier field id
- check if record key fields are all required
> only set record key field in iceberg if it is a required field

- core/src/test/java/io/onetable/iceberg/TestIcebergSourceClient.java
- pom.xml
Fixes #309 
Upgrade Iceberg version from 1.3 to 1.4
New version will enable direct FileIO for public clouds. This feature allows OneTable to read and write data directly from cloud storage without using Hadoop FileSystem API, which improves performance and reduces overhead.
For example see: [ADLSFileIO](https://github.com/apache/iceberg/pull/8303/files)
This pull request is a trivial without any test coverage.
> Upgrade Iceberg version

- pom.xml
Issue #308 
Fix an access denied issue on copying a file in S3.
Bumped the `hadoop-aws` version from `3.2.2` to `3.3.1`
This pull request is a library version change. Project builds correctly and migration from Delta to Iceberg works using S3.
> Upgrade hadoop-aws version

- core/src/main/java/io/onetable/delta/DeltaActionsConverter.java
- core/src/main/java/io/onetable/delta/DeltaDataFileExtractor.java
- core/src/main/java/io/onetable/delta/DeltaDataFileUpdatesExtractor.java
Fixes #325 
The current code in the DeltaClient generates unnecessary objects when computing the file diff to find new and removed files. The process first converts all Delta Actions of the current delta log's snapshot to OneDataFiles, uses OneDataFiles to compute the diff, and then converts the resulting OneDataFiles collection back to Delta Action objects for writing. There is a round trip from Delta Action to OneDataFiles here. For large tables with thousands of Actions in a snapshot, this results in the creation of a large number of objects unnecessarily.
This change optimizes this process by skipping the unnecessary steps of converting delta actions from the previous snapshot into OneDataFiles and then back into delta actions. This optimizations does not change the behavior of the …
> Optimize object creation for new Delta snapshot

- api/src/main/java/io/onetable/model/storage/DataFilesDiff.java
- api/src/main/java/io/onetable/model/storage/OneDataFilesDiff.java
- api/src/test/java/io/onetable/model/storage/TestDataFilesDiff.java
- api/src/test/java/io/onetable/model/storage/TestOneDataFilesDiff.java
- core/src/main/java/io/onetable/delta/DeltaDataFileUpdatesExtractor.java
- core/src/main/java/io/onetable/iceberg/IcebergDataFileExtractor.java
- core/src/main/java/io/onetable/iceberg/IcebergDataFileUpdatesSync.java
- core/src/test/java/io/onetable/iceberg/TestIcebergSync.java
Fixes #329 
This is a performance optimization change and extends the improvements added to DeltaClient to IcebergClient.
The current code in the Iceberg client generates unnecessary objects when computing the file diff to find new and removed files. The process first converts all table format data files of the current snapshot to OneDataFiles, uses OneDataFiles to compute the diff, and then converts the resulting OneDataFiles collection back to table format data file objects for writing. There is an unnecessary round trip here. For large tables with thousands of data files in a snapshot, this results in the creation of a large number of objects unnecessarily.
This change optimizes this process by skipping the unnecessary conversions. This optimization does not change the behavior of the …
> Avoid unnecessary Iceberg datafile to onedatafile conversions

- core/src/main/java/io/onetable/delta/DeltaClient.java
- core/src/main/java/io/onetable/delta/DeltaClientUtils.java
- core/src/main/java/io/onetable/delta/DeltaDataFileUpdatesExtractor.java
- core/src/main/java/io/onetable/delta/DeltaSourceClient.java
- core/src/main/java/io/onetable/delta/DeltaTableExtractor.java
- core/src/test/java/io/onetable/ITOneTableClient.java
- core/src/test/java/io/onetable/client/TestTableFormatClientFactory.java
- core/src/test/java/io/onetable/delta/ITDeltaSourceClient.java
- core/src/test/java/io/onetable/delta/TestDeltaStatsExtractor.java
- core/src/test/java/io/onetable/delta/TestDeltaSync.java
- core/src/test/java/io/onetable/hudi/HudiTestUtil.java
- hudi-support/extensions/pom.xml
- hudi-support/extensions/src/test/java/io/onetable/hudi/sync/TestOneTableSyncTool.java
- pom.xml
Fixes #340 
Support for Deletion Vectors has been added in Delta Lake version 2.4. The upgrade also requires updating the spark runtime version to 3.4+
In addition to chaning the version of the dependencies, this change also incorporates all the backward incompatible changes in the Delta API.
1. getSnapshotAt change: it does not accept a optional timestamp (2nd method argument) anymore. This argument was not provided / used by XTable and can safely be ignored in all invocations.
2. addFile api change: It now requires information about DeleteVector as a parameter. As Deletion vectors writing is not supported in the current version of XTable, a null is provided to the addFile method call.
3. update transaction api change: It now requires an Catalyst Expression object, instead of a generic …
> Upgrade Delta Lake version:2.4 for deletion vector support

- core/src/main/java/io/onetable/hudi/HudiDataFileExtractor.java
- core/src/test/java/io/onetable/TestAbstractHudiTable.java
- core/src/test/java/io/onetable/hudi/ITHudiSourceClient.java
This PR fixes the bug (#331) in data file extraction from the Hudi restore metadata when the restore metadata contains log files in the `successDeleteFiles` field, like below.
```
{"startRestoreTime": "20240206231939820", "timeTakenInMillis": 395672, "instantsToRollback": ["20240206224826804", "20240206184945238", "20240206033415397", "20240206033231467", "20240205235951898", "20240205235922526", "20240205215621113", "20240205215536114", "20240205215451379", "20240205211110380", "20240205210452584", "20240205210142189", "20240205210001428"],
"hoodieRestoreMetadata": {"20240205210452584":
[{"HoodieRollbackMetadata": {"startRollbackTime": "20240206232452651", "timeTakenInMillis": 1766, "totalFilesDeleted": 276, "commitsRollback": ["20240205210452584"], "partitionMetadata": {"2024-02-03": …
```
> Fix data file extraction from Hudi restore metadata with log files

- core/src/main/java/io/onetable/delta/DeltaSourceClient.java
- core/src/test/java/io/onetable/delta/TestDeltaSync.java
- pom.xml
Upgrade spotless-maven-plugin to latest to benefit from recent fixes and improvements.
- Upgrade spotless-maven-plugin from 2.27.2 to 2.43.0
- Add some additional import order rules to retain the existing order and avoid having a large diff due to fixes/changes in the plugin. If a different order is desired then it can be done in a separate commit.
- Add missing spaces between scala and io imports in 2 files.
> Upgrade spotless-maven-plugin from 2.27.2 to 2.43.0

- .asf.yaml
This PR creates the .asf.yaml file for the project. More information about the supported options can be found here: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md
The current options basically preserve the behavior that was enabled before the transfer to the ASF organization.
> Create .asf.yaml file

- .mvn/extensions.xml
- pom.xml
General build maintenance fixes. Add maven-build-cache extension to speedup builds and align hadoop dependency versions across the build.
- *Align hadoop dependency versions to version 3.3.6 (provided)*
- *Add maven-build-cache-extension to speedup builds when using Maven 3.9.x/4.x*
This pull request is already covered by existing tests.
> Add maven-build-cache extension to speedup builds and pin hadoop dependency version

- README.md
- core/src/main/java/org/apache/xtable/delta/DeltaActionsConverter.java
- core/src/main/java/org/apache/xtable/delta/DeltaIncrementalChangesState.java
- core/src/test/java/org/apache/xtable/delta/ITDeltaSourceClient.java
- core/src/test/java/org/apache/xtable/testutil/Issues.java
This fixes some URL breakage produced by #374
- *Update URLs to the new package structure*
- *Remove TODOs with URLs for already fixed issues*
This pull request is already covered by existing tests
> Fix broken links after move to Apache and rename from onetable (#384)

- pom.xml
This will simplify maven plugin maintenance so we don't need to update plugins independently to be up to date.
Maven plugin dependencies will be updated by upgrading the parent POM version.
This also removes warnings for non pinned plugin versions and updates some of them.
- *Added parent pom to root project*
- *Remove explicit plugin versions*
This pull request is already covered by existing tests.
> Make build depend on Apache Maven Parent POM

- README.md
Support for awsCredentialsProvider as a command like argument was removed in PR-5 in favor of a more generic config input based on hadoopConfig. However, the Readme was not updated accordingly. This change fixes the README.
Address #401
> Fix README, remove outdated aws credentials param

- demo/docker-compose.yaml
- demo/notebook/demo.ipynb
Fixed #429
Fix UnknownHostException: host.docker.internal in docker demo under Linux OS.
```
MetaException(message:Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: java.net.UnknownHostException: host.docker.internal
at org.apache.thrift.transport.TSocket.open(TSocket.java:226)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:478)
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:245)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAc …
```
> [Demo] Fix UnknownHostException: host.docker.internal in docker demo

- .github/workflows/license-check.yaml
- .licenserc.yaml
- README.md
> License header check

- pom.xml
- xtable-utilities/pom.xml
Addresses #446 
Upgrades or removes some dependencies that were flagged by security tooling for identifying vulnerable dependencies.
- Exclude zookeeper as we do not require it and the version had a vulnerability reported
- Upgrade jackson to avoid vulnerabilities in the library modules and its dependencies
- Remove Hive from the path - this jar was just included for the utilities bundle but users can add their own implementation to the path
- netty - upgrade version by using BOM to ensure consistent version
- jetty - upgrade version by using BOM to ensure consistent version
- Pin versions for transitive dependencies like: snappy, commons-compress, commons-configuration, ivy, jettison, numbus-jose-jwt
- Synced Hudi -> Iceberg, Delta and Delta -> Iceberg, Hudi on S3
- Validate that all …
> [446] Upgrade or remove dependencies with known vulnerabilities

- demo/start_demo.sh
- website/docs/how-to.md
Fixed #436.
We can only cd to the demo directory to execute the script currently, this purpose of this issue is to improve usability.
Update `start_demo.sh` script.
*(or)*
(or)
*(example:)*
- *Added HudiSchemaEvolutionTest to verify the change.*
> [Demo] Make start_demo script easier to call

- .github/workflows/mvn-license-check.yml
- README.md
- ci.md
- demo/README.md
- pom.xml
- website/README.md
- xtable-core/src/test/resources/schemas/basic_schema.avsc
- xtable-hudi-support/xtable-hudi-support-extensions/README.md
- #449
As we known, `apache-rat` plugin cat verify whether source code matches standards like the [ASF Source Header and Copyright Notice Policy](https://www.apache.org/legal/src-headers.html), and this plugin is widely used in many projects, like hudi, flink ...
The `spotless-maven-plugin` can only check several file types, so it can't fits our need.
https://creadur.apache.org/rat/apache-rat-plugin/usage.html
Manually verified the change by running a job locally.
> [Infra] Introduce apache rat plugin to xtable project

- .github/workflows/mvn-ci-build.yml
- #438
Due to the Azure CI is always unstable, so we use `Github Action` to try to solve this problem.
locally.
> [Infra] Support GitHub Action build the xtable project

- xtable-core/src/main/java/org/apache/xtable/delta/DeltaStatsExtractor.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaStatsExtractor.java
Handles an edge case where the AddFile object has not column stats
- Return empty list if column stats is null or empty
- Added unit test case
> [481] Handle null stats in Delta AddFile

- pom.xml
* Upgrade the parent pom version to the latest (33) to use more recent versions for the various plugins and take advantage of the updated properties (e.g., `project.build.outputTimestamp`) which are taken into account for jar generation, NOTICE files, etc.
> Upgrade parent pom version from 31 to 33

- pom.xml
#509 
Configure `maven-remote-resources-plugin` to use "Apache XTable (incubating) as the product name inside the NOTICE files.
```
$ mvn clean install -DskipTests
$ for i in `find . -name "*jar"`; do echo $i; jar xf $i META-INF; cat META-INF/NOTICE; done
```
> Incorrect product name and distribution years in NOTICE file inside jars (#509)

- pom.xml
The javadoc goal fails since we are trying to create Javadoc for JDK7 while the code has language features of JDK8.
```
mvn org.apache.maven.plugins:maven-javadoc-plugin:javadoc -Prelease
```
There are various errors such as the one shown below.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:javadoc (default-cli) on project xtable-api: An error has occurred in Javadoc report generation:
[ERROR] Exit code: 1
[ERROR] /home/stamatis/Projects/Apache/incubator-xtable/xtable-api/src/main/java/org/apache/xtable/spi/sync/TableFormatSync.java:74: error: lambda expressions are not supported in -source 1.7
[ERROR]                 target -> target.syncFilesForSnapshot(snapshot.getPartitionedDataFiles()),
[ERROR]                        ^
[ERROR]   (use -source 8 …
```
> Error when generating Javadoc due to old JDK7 compiler version

- pom.xml
- release/release_guide.md
- release/scripts/create_source_release.sh
- release/scripts/cut_release_branch.sh
- release/scripts/deploy_staging_jars.sh
- release/scripts/validate_source_binary_files.sh
- release/scripts/validate_source_copyright.sh
- release/scripts/validate_source_rat.sh
- release/scripts/validate_staged_bundles.sh
- release/scripts/validate_staged_release.sh
https://github.com/apache/incubator-xtable/issues/486
Add the release guide/process for Apache XTable, the guide has been added based on the guidelines provided by Apache. 
https://infra.apache.org/release-publishing 
https://www.apache.org/legal/release-policy.html 
Special guidelines for incubating projects.
https://incubator.apache.org/guides/releasemanagement.html#best-practice 
https://infra.apache.org/release-publishing.html#uploading
- *Added release guide*
- *Added scripts for generating GPG keys*
- *Added scripts for deploying jars and artifacts signed by the GPG keys* 
This pull request is a release guide without any test coverage, the guide will be run in a dry-run mode to ensure …
> [486] Add release guide for XTable

- .github/workflows/site-deploy.yml
The previous PR removed the downloads page from the website and worked locally but GH action had this config as true so downloads page wasn't removed completely from http and was lingering around.
https://xtable.apache.org/releases/downloads/  
https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-keeping-existing-files-keep_files
- *Fix GH action to remove pages*
> Set keep_files as false in GH action for site deploy to remove lingering pages

- pom.xml
- xtable-api/pom.xml
- xtable-core/pom.xml
- xtable-hudi-support/pom.xml
- xtable-hudi-support/xtable-hudi-support-extensions/pom.xml
- xtable-hudi-support/xtable-hudi-support-utils/pom.xml
- xtable-utilities/pom.xml
This pull request aims to address issue [#531](https://github.com/apache/incubator-xtable/issues/531)
Adding the <licenses> tag to xtable project and updating the project name.
* Added the <licenses> and <organization> in the xtable parent project
```xml
<licenses>
<license>
<name>Apache License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
</license>
</licenses>
<organization>
<name>The Apache Software Foundation</name>
<url>https://www.apache.org</url>
</organization>
```
* Updated the project name for each module, for example
```xml
<name>XTable Parent Project</name>
```
Verified by running `$ mvn clean install -DskipTests -U` locally.
> [531] xtable poms are missing license details.

- pom.xml
- xtable-core/pom.xml
This pull request aims to address issues [#530](https://github.com/apache/incubator-xtable/issues/530)
Removing the hardcoded scala version for jackson-module-scala in xtable parent project and xtable-core projects.
* Removed the hard coded scala version i.e `2.12` and replaced with `${scala.version.prefix}`.
```xml
<dependency>
<groupId>com.fasterxml.jackson.module</groupId>
<artifactId>jackson-module-scala_${scala.version.prefix}</artifactId>
<version>${jackson.version}</version>
</dependency>
```
Verified by running `$ mvn clean install -DskipTests -U` locally.
> [530] xtable-core pom has a hardcoded scala version for jackson-module-scala

- xtable-utilities/pom.xml
Based on feedback from general@incubator.apache.org, excluding xtable-utilities bundle as part of release i.e mvn deploy. 
- *Exclude xtable-utilities from release*
Validated it by running mvn deploy in dry run mode and confirmed it through logs.
```
[INFO] --- deploy:3.1.1:deploy (default-deploy) @ xtable-utilities ---
[INFO] Skipping artifact deployment
```
> [536] Exclude xtable-utilities from mvn deploy

- xtable-core/src/main/java/org/apache/xtable/delta/DeltaValueConverter.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaValueConverter.java
The pr aims to fix: https://github.com/apache/incubator-xtable/issues/524.
When reading the delta snapshot and load the information into Delta object AddFile, the non-numeric values of float or double type (example, "NaN", "-Infinity") from col stats become string type. These special values need special handling and this pr used the same idea how delta new API handled this: https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/data/DefaultJsonRow.java#L210
- Add logic to handle special String value ("NaN", "-Infinity", "Infinity") when column type is Double or Float during translating Delta column stat to InternalType 
- Add unit test
- Added unit test for this edge case
> Fix the edge case when handling non numeric values of double type in delta stats

- xtable-api/src/main/java/org/apache/xtable/model/schema/InternalSchema.java
- xtable-api/src/main/java/org/apache/xtable/model/schema/InternalType.java
- xtable-core/src/main/java/org/apache/xtable/avro/AvroSchemaConverter.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaSchemaExtractor.java
- xtable-core/src/main/java/org/apache/xtable/hudi/HudiPartitionValuesExtractor.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/GenericTable.java
- xtable-core/src/test/java/org/apache/xtable/ITConversionController.java
- xtable-core/src/test/java/org/apache/xtable/TestIcebergTable.java
- xtable-core/src/test/java/org/apache/xtable/avro/TestAvroSchemaConverter.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergDataHelper.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergSchemaExtractor.java
Aim to address #112 
Create a UUID type in OneType and handle it appropriately in all converters. Only Iceberg has a concept of a UUID and it is a fixed size byte array in the underlying parquet files. We should aim to preserve the metadata that this byte array came from a UUID for round trip conversions.
- Add a `UUID` type in InternalType
- Handle UUID internal type in Iceberg/Delta/Avro(for Hudi) Converters as a fixed-size byte array
- Adding unit tests
This pull request is already covered by existing tests, all existing tests should pass
> [112] Add a UUID Type

- Dockerfile
- README.md
- demo/start_demo.sh
- pom.xml
- website/docs/biglake-metastore.md
- website/docs/fabric.md
- website/docs/glue-catalog.md
- website/docs/hms.md
- website/docs/how-to.md
- website/docs/unity-catalog.md
- xtable-core/pom.xml
- xtable-hudi-support/xtable-hudi-support-extensions/pom.xml
- xtable-utilities/pom.xml
This pull request aims to address issues [#529](https://github.com/apache/incubator-xtable/issues/529)
To support building the xtable with multiple scala versions i.e 2.12 and 2.13. 
* Added scala12 and scala13 version properties in pom.xml file.
```xml
<scala12.version>2.12.15</scala12.version>
<scala13.version>2.13.8</scala13.version>
```
* Added profiles to support scala12 and scala13
```xml
<profile>
<id>scala-2.12</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<properties>
<scala.version>${scala12.version}</scala.version>
<scala.version.prefix>2.12</scala.version.prefix>
</properties>
<build>
<pluginManagement/>
</build>
</profile>
```
Run `$ mvn clean install -DskipTests -U` locally.
**Note:** Hudi does not yet support Scala 2.13 jars, so the scala-2.13 …
> [529] Build xtable with scala version(s)

- release/release_guide.md
- release/scripts/create_source_release.sh
- release/scripts/validate_staged_bundles.sh
Excludes xtable-utilities from release scripts for generating source and validations.
- *Excludes xtable-utilities from release scripts*
Verified the scripts through dry run and used them for releasing 0.2.0-incubating rc1 as well.
> [551] Exclude xtable-utilities from release guide

- .github/workflows/mvn-ci-build.yml
- pom.xml
Avoids long running github actions pipelines when there is an issue with a PR
- Set timeout on the Github Action pipeline
- Add timeout for forked process in surefire and failsafe
> [561] Add timeout to Github Action 

- pom.xml
Addresses #560 
Updates version based on dependabot's findings
- Set protobuf dependencies to 3.25.5
- Update hadoop dependency which brings in the proto dependency
> [560] Increment Protobuf version due to vulnerability

- xtable-api/pom.xml
- xtable-core/pom.xml
- xtable-hudi-support/xtable-hudi-support-extensions/pom.xml
- xtable-hudi-support/xtable-hudi-support-utils/pom.xml
- xtable-utilities/pom.xml
Helps avoid confusion around a dependency's scope when working within or inspecting a module
- Define the scope of any dependency that is not simply `compile` in our child poms
> [564] mirror parent dependency scopes in child pom files

- LICENSE
- NOTICE
The final outcome from https://issues.apache.org/jira/browse/LEGAL-684 advises to not include dependencies from other ASF projects in LICENSE and NOTICE files.
- *Updated LICENSE and NOTICE files to reflect feedback LEGAL-684*
> [551] Remove dependencies in LICENSE and NOTICE files based on feedback in LEGAL-684

- xtable-hudi-support/xtable-hudi-support-extensions/pom.xml
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/LICENSE
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/licenses/LICENSE-antlr4-runtime
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/licenses/LICENSE-checker-qual
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/licenses/LICENSE-javax-annotation-api
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/licenses/LICENSE-paranamer
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/resources/META-INF/licenses/LICENSE-slf4j-api
The bundled jar in xtable-hudi-support-extensions needs a different version of LICENSE and NOTICE file as it bundles MIT and BSD-3 license dependencies. Excluded hudi-common's transitive dependencies (hbase, hadoop etc.) from xtable-core by making it as provided to avoid the following non ASF compliant dependencies  in the class path. Refer xtable-hudi-support-extensions tab in the [sheet](https://docs.google.com/spreadsheets/d/1XBCZBeWqF2D5d1L4H9fRQ1QLarJq4tLgIEgnGiNdoV8/edit?usp=sharing). 
1. org.openjdk.jol:jol-core:jar:0.16 
2. javax.activation:javax.activation-api:jar:1.2.0
3. javax.ws.rs:javax.ws.rs-api:jar:2.1.1
4. org.glassfish.web:javax.servlet.jsp:jar:2.3.2
5. org.glassfish:javax.el:jar:3.0.0
6. …
> [551] Create separate LICENSE and NOTICE files for xtable-hudi-support-extensions

- xtable-core/src/main/java/org/apache/xtable/delta/DeltaSchemaExtractor.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergSchemaSync.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergSchemaSync.java
Aim to address https://github.com/apache/incubator-xtable/issues/525
It is expected to capture the comments and sync the comments of field when syncing schema. The PR makes the comments of schema fields are captured and synced correctly.
- For Delta target, extract the comment from internal schema and add to Spark schema representative. 
- For Iceberg target, make sure any difference of comments is captured during syncSchema() and the schema is updated with new comments.
- *Added unit tests to test the comments in Iceberg schema sync test class*
- *Added comments in Delta schema extractor test class*
> Iceberg and Delta target: sync schema field comments

- .github/workflows/site-deploy.yml
The local version of the website is not getting deployed to https://xtable.incubator.apache.org/, setting the keep_files flag as false to see if it works.
- *Setting the keep_files config to false to see if website docs upload works*
The website builds locally using npm.
> [551] Try enabling keep_files as false in GH action for downloads

- website/static/.asf.yaml
Restore the .asf.yaml file that was accidentally removed by https://github.com/apache/incubator-xtable/commit/493e1878dc94c3d8f29675132f03e3941e29b470 as a side-effect of changing the keep_files configuration.
Add .asf.yaml  under static directory to appear at the root of https://github.com/apache/incubator-xtable
Cannot be tested without committing to the repo.
> Site content is not deployed due to missing .asf.yaml file

- xtable-core/src/test/java/org/apache/xtable/TestSparkDeltaTable.java
- xtable-core/src/test/java/org/apache/xtable/delta/ITDeltaDeleteVectorConvert.java
This change uses the correct table row deletion operation in the deleteRows method, which previously performed merge-with-delete operation instead of a true delete. Since most test tables do not have delete vectors enabled, this change does not break existing tests. To validate the change, a new test has been added with deletion vector property set for the test table. However, the actual XTable conversion test is not part of this change, as it requires more changes in the DeltaSource to correctly handle the deletion files. This will be addressed in future update.
This pull request is related to test fixes.
Fixes #588
> Execute correct delete operation in delta tests

- xtable-core/src/main/java/org/apache/xtable/delta/DeltaActionsConverter.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaConversionSource.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaStatsExtractor.java
- xtable-core/src/test/java/org/apache/xtable/delta/ITDeltaDeleteVectorConvert.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaActionsConverter.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaStatsExtractor.java
This change fixes the issue of double counting a data file. When adding deletion vector information to an existing data file, Delta Lake adds two entries in the commit log: one to remove the old entry (which has empty or outdated delete vector information) and another to add the updated delete vector information. Both entries are for the same data file path which was already added by an existing commit. While XTable currently doesn’t convert deletion vectors, it can avoid duplicate counting of the data file by ignoring the entries created when delete vector information is updated.
Additionally, this change detects new data file stats in logs that are not recognized and translated by XTable. Name of such unrecognized stats are logged. The fix ensures that new stats does not break parsing …
> Fix commit log parsing of Delta tables with delete vector

- xtable-core/src/main/java/org/apache/xtable/conversion/ConversionController.java
- xtable-core/src/main/java/org/apache/xtable/conversion/ConversionUtils.java
- xtable-core/src/test/java/org/apache/xtable/ITConversionController.java
- xtable-core/src/test/java/org/apache/xtable/conversion/TestConversionUtils.java
When iceberg tables are used as source, they can have different basePath and dataPaths, when synchronizing these tables to hudi and delta, the .hoodie and _delta_log directories should be present in `basePath/data/.hoodie`, the current code generates the metadata at `basePath/.hoodie`
- *Fixes the target base paths when source table format is ICEBERG with different basePath and dataPath*
*(example:)*
- *xtable-core/src/test/java/org/apache/xtable/ITConversionController.java*
- *xtable-core/src/test/java/org/apache/xtable/conversion/TestConversionUtils.java*
> Normalize basePath in targetTables in ConversionController

- rfc/template.md
Introduce RFC template to propose/review new technical specs in the project.  
- *Add RFC template*
> [590] Add RFC template for XTable

- rfc/template.md
The RFC template was reverted in previous commit, adding the template back. 
https://github.com/apache/incubator-xtable/pull/604 
- *Add RFC template*
> [590] Add RFC template for XTable 

- pom.xml
- xtable-utilities/pom.xml
- xtable-utilities/src/main/resources/xtable-hadoop-defaults.xml
Hadoop and AWS sdk version upgrade
We need aws sdk v2 for Glue catalog sync implementation (https://github.com/apache/incubator-xtable/pull/599) and hadoop 3.4.0 has compatibility issues (https://issues.apache.org/jira/browse/HADOOP-19241) with aws sdk v2 which has been fixed in hadoop 3.4.1, so this PR upgrades
- hadoop to 3.4.1
- aws sdk to v2
> [590] Hadoop and AWS sdk version upgrade

- xtable-core/src/main/java/org/apache/xtable/delta/DeltaValueConverter.java
- xtable-core/src/main/java/org/apache/xtable/hudi/HudiFileStatsExtractor.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaValueConverter.java
- xtable-core/src/test/java/org/apache/xtable/hudi/TestHudiFileStatsExtractor.java
- xtable-core/src/test/java/org/apache/xtable/testutil/ColumnStatMapUtil.java
Addresses bug found in #608 
When converting the column stats to bytes in Iceberg, the `BigDecimal#unscaledValue` is called. If the value has the wrong scale, then the serialization and then deserialization will result in a different value.
- Set the scale when reading back the column stats from the Hudi Metadata Table
- Set the scale when parsing the Delta Log stats
- Fixed incorrect unit test setup for Hudi column stats extraction
- Added new tests for converting the column stats values for Delta Lake
> [608] Ensure column stats for decimal fields have proper scale set

- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergConversionSource.java
- Fixes a bug where the column stats were not populated when reading snapshots
- Include column stats when reading the snapshot
- Updated the unit tests to validate that the column stats are set for snapshots and when reading just the changes for that commit
> [615] Add Iceberg stats when reading snapshot

- website/README.md
- website/community/sync.md
- website/docusaurus.config.js
- website/static/index.html
Add community sync page for Apache XTable(Incubating). Following Monday 8AM PST schedule based on response from 
dev channel. 
https://lists.apache.org/thread/30gtw1qnk0jyhv8xmhtoox662sj0mf86 
- *Add community sync page for Apache XTable(Incubating)*
Verified the page loads locally and all links are valid.
> Add community sync page for XTable

- xtable-api/src/main/java/org/apache/xtable/conversion/ConversionConfig.java
- xtable-api/src/main/java/org/apache/xtable/conversion/ExternalCatalogConfig.java
- xtable-api/src/main/java/org/apache/xtable/conversion/TargetCatalogConfig.java
- xtable-api/src/main/java/org/apache/xtable/model/storage/CatalogType.java
- xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSyncClient.java
- xtable-core/pom.xml
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogConversionFactory.java
- xtable-core/src/main/java/org/apache/xtable/conversion/ConversionController.java
- xtable-core/src/main/java/org/apache/xtable/conversion/ConversionUtils.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergCatalogConfig.java
- xtable-core/src/test/java/org/apache/xtable/catalog/TestCatalogConversionFactory.java
- xtable-core/src/test/java/org/apache/xtable/conversion/TestConversionController.java
- xtable-core/src/test/java/org/apache/xtable/testutil/ITTestUtils.java
- xtable-core/src/test/resources/META-INF/services/org.apache.xtable.spi.extractor.CatalogConversionSource
- xtable-core/src/test/resources/META-INF/services/org.apache.xtable.spi.sync.CatalogSyncClient
- xtable-utilities/pom.xml
- xtable-utilities/src/main/java/org/apache/xtable/utilities/RunCatalogSync.java
- xtable-utilities/src/main/java/org/apache/xtable/utilities/RunSync.java
- xtable-utilities/src/test/java/org/apache/xtable/utilities/ITRunCatalogSync.java
- xtable-utilities/src/test/java/org/apache/xtable/utilities/TestRunCatalogSync.java
- xtable-utilities/src/test/resources/catalogConfig.yaml
Introduced `RunCatalogSync` utility which does the following on a high level. This unblocks the ability to sync tables from a source catalog to multiple target catalogs, you can look at the sample configuration here `xtable-utilities/src/test/resources/catalogConfig.yaml`
See RFC for more details on the deign and flow chart -> https://github.com/apache/incubator-xtable/pull/605
- *Add. ability to synchronize tables between source and target catalogs*
*(example:)*
- *xtable-utilities/src/test/java/org/apache/xtable/utilities/TestRunCatalogSync.java*
> [590] Add RunCatalogSync utility for synchronizing tables across catalogs

- xtable-api/src/main/java/org/apache/xtable/model/stat/FileStats.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaActionsConverter.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaStatsExtractor.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaStatsExtractor.java
Addresses https://github.com/apache/incubator-xtable/issues/102
-  Update how to get the number of records from Delta source 
- Side effect, it also fixed the edge case when columnStats list is empty, the number of records becomes 0
- added a line of test
> Delta source: add record count for DataFile

- pom.xml
- xtable-api/src/main/java/org/apache/xtable/model/storage/CatalogType.java
- xtable-hive-metastore/pom.xml
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogConfig.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogConversionSource.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogSyncClient.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogTableBuilderFactory.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSClientProvider.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSSchemaExtractor.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/table/IcebergHMSCatalogTableBuilder.java
- xtable-hive-metastore/src/main/resources/META-INF/services/org.apache.xtable.spi.extractor.CatalogConversionSource
- xtable-hive-metastore/src/main/resources/META-INF/services/org.apache.xtable.spi.sync.CatalogSyncClient
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/HMSCatalogSyncClientTestBase.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSCatalogConfig.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSCatalogConversionSource.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSCatalogSyncClient.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSCatalogTableBuilderFactory.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSSchemaExtractor.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/table/TestIcebergHMSCatalogTableBuilder.java
- xtable-utilities/pom.xml
https://github.com/apache/incubator-xtable/issues/590
Added support for syncing a source table to HMS catalog in Iceberg table format
- Created a new module **xtable-hive-metastore**
- Added **HMSCatalogSyncClient** implementation for syncing **InternalTable** to HMS catalog in Iceberg table format
- Added **HMSCatalogConversionSource** implementation for creating **SourceTable** from HMS table identifier
- Added HMSSchemaExtractor for generating Hive compatible schema from **InternalSchema**
- Added unit tests
- Manually verified the change by running a job locally
> [590] Add Iceberg HMS Catalog Sync implementation

- xtable-aws/src/main/java/org/apache/xtable/glue/GlueCatalogTableBuilderFactory.java
- xtable-aws/src/main/java/org/apache/xtable/glue/GlueSchemaExtractor.java
- xtable-aws/src/main/java/org/apache/xtable/glue/table/DeltaGlueCatalogTableBuilder.java
- xtable-aws/src/test/java/org/apache/xtable/glue/GlueCatalogSyncTestBase.java
- xtable-aws/src/test/java/org/apache/xtable/glue/TestGlueSchemaExtractor.java
- xtable-aws/src/test/java/org/apache/xtable/glue/table/TestDeltaGlueCatalogTableBuilder.java
- xtable-aws/src/test/java/org/apache/xtable/glue/table/TestIcebergGlueCatalogTableBuilder.java
https://github.com/apache/incubator-xtable/issues/590
Added support for syncing an InternalTable to Glue catalog in Delta table format
Added **DeltaGlueCatalogTableBuilder** class to provide create / update table request for delta table format for syncing to Glue catalog
- Added unit tests
- Manually verified the change by running a job locally
> [590] Add Delta Glue Catalog Sync implementation

- pom.xml
- xtable-hive-metastore/pom.xml
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogSyncClient.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/HMSCatalogTableBuilderFactory.java
- xtable-hive-metastore/src/main/java/org/apache/xtable/hms/table/DeltaHMSCatalogTableBuilder.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/HMSCatalogSyncClientTestBase.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/TestHMSCatalogTableBuilderFactory.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/table/TestDeltaHMSCatalogTableBuilder.java
- xtable-hive-metastore/src/test/java/org/apache/xtable/hms/table/TestIcebergHMSCatalogTableBuilder.java
https://github.com/apache/incubator-xtable/issues/590
Added support for syncing an InternalTable to HMS catalog in Delta table format
Added **DeltaHMSCatalogTableBuilder** class to provide create / update table request for delta table format
- Added unit tests
- Manually verified the change by running a job locally
> [590] Add Delta HMS Catalog Sync implementation

- xtable-core/pom.xml
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogPartition.java
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogPartitionEvent.java
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogPartitionSyncOperations.java
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogPartitionSyncTool.java
- xtable-core/src/main/java/org/apache/xtable/catalog/CatalogUtils.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaConversionTarget.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaSchemaExtractor.java
- xtable-core/src/main/java/org/apache/xtable/hudi/HudiTableManager.java
- xtable-core/src/main/java/org/apache/xtable/hudi/catalog/HudiCatalogPartitionSyncTool.java
- xtable-core/src/main/java/org/apache/xtable/hudi/catalog/HudiCatalogTableUtils.java
- xtable-core/src/main/java/org/apache/xtable/hudi/catalog/HudiInputFormatUtils.java
- xtable-core/src/main/java/org/apache/xtable/schema/SparkSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/hudi/catalog/TestHudiCatalogPartitionSyncTool.java
- xtable-core/src/test/java/org/apache/xtable/hudi/catalog/TestHudiCatalogTableUtils.java
- xtable-core/src/test/java/org/apache/xtable/hudi/catalog/TestHudiInputFormatUtils.java
- xtable-core/src/test/java/org/apache/xtable/schema/TestSparkSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/testutil/ITTestUtils.java
https://github.com/apache/incubator-xtable/issues/590
Added support for syncing a source table to HMS catalog in Hudi table format
- Added HudiPartitionSyncTool to sync the hudi partitions to catalogs
- AddedCatalogPartitionSync operations to support partitions sync to HMS and Glue
- Added unit tests
- Manually verified the change by running a job locally
> [590] Add Hudi HMS Catalog Sync implementation

- rfc/rfc-2/2 - Deletion Info Conversion.md
Fixes #631 
This is a documentation change only. This document provides a high-level proposal of deletion vector conversion in XTable, focusing on the current implementation of deletion vectors in Delta Lake and Iceberg.
> Add change proposal for conversion of deletion vectors

- xtable-core/src/test/java/org/apache/xtable/hudi/TestBaseFileUpdatesExtractor.java
Fixes #658 
This change fixes a test only. The test is currently comparing the equality of two lists, which would fail if the order of elements in the lists differ. Since the test is order insensitive, the right solution is to convert the lists to sets. Set equality is order independent.
> Fix flaky test, ignore order of elements in list validation

- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergConversionSource.java
- xtable-core/src/test/java/org/apache/xtable/TestIcebergTable.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/ITIcebergConversionSource.java
> Modified incremental safe check which does not depend on snapshots list order

- xtable-api/src/main/java/org/apache/xtable/model/schema/InternalPartitionField.java
- xtable-api/src/main/java/org/apache/xtable/model/schema/PartitionTransformType.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaPartitionExtractor.java
- xtable-core/src/main/java/org/apache/xtable/hudi/HudiTableManager.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergPartitionSpecExtractor.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergPartitionValueConverter.java
- xtable-core/src/test/java/org/apache/xtable/ITConversionController.java
- xtable-core/src/test/java/org/apache/xtable/TestIcebergTable.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaPartitionExtractor.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergDataHelper.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergPartitionSpecExtractor.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergPartitionValueConverter.java
Addresses #668 
Adds support for handling Iceberg's Bucket partitioning when converting to Delta Lake. 
- Skips handling of Void partition which will always return a null value
- Handle bucket partitioning by adding a new field in InternalPartitionField to track partitioning options like number of buckets
- Delta Lake support is added by using generated column to represent the partition similar to what we do for date based partitioning
- Added unit tests for conversion cases
- Added integration test for Iceberg to Delta with bucket partitioning and void partition to test case reported
> [668] Support bucket partition transform for Iceberg Sources and Delta Targets

- pom.xml
- xtable-core/src/main/java/org/apache/xtable/avro/AvroSchemaConverter.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaConversionTarget.java
- xtable-core/src/main/java/org/apache/xtable/delta/DeltaSchemaExtractor.java
- xtable-core/src/main/java/org/apache/xtable/iceberg/IcebergSchemaExtractor.java
- xtable-core/src/main/java/org/apache/xtable/schema/SparkSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/avro/TestAvroSchemaConverter.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/delta/TestDeltaSync.java
- xtable-core/src/test/java/org/apache/xtable/iceberg/TestIcebergSchemaExtractor.java
- xtable-core/src/test/java/org/apache/xtable/schema/TestSparkSchemaExtractor.java
1. Handle `timestamp_ntz` in delta target, ensured backwards compatibility by using the min and max writer version from `deltaLog.snapshot()`
2. Handle `timestamp_ntz` for iceberg target as well. 
- *Handle timestamp_ntz in delta target*
- *Handle `timestamp_ntz` for iceberg target as well*
*(example:)*
- *testTimestampNtz*
> Handle timestamp_ntz in delta and iceberg

- README.md
- website/community/sync.md
Add guidelines for stale PR's in README and website.
- *Add guidelines for stale PR's in README and website*
> [678] Add contribution guidelines to reflect stale PR's guidelines

- xtable-aws/pom.xml
- xtable-hive-metastore/pom.xml
Found few problems in 0.3.0-rc1 staged artificats, abandoned the release as few modules were missing.
- *Fixed pom.xml configuration for missing modules*
> [678] Avoid skipping xtable-aws and xtable-hive-metastore in mvn deploy

- xtable-api/src/main/java/org/apache/xtable/annotations/Evolving.java
- xtable-api/src/main/java/org/apache/xtable/annotations/Stable.java
- xtable-api/src/main/java/org/apache/xtable/model/sync/ErrorDetails.java
- xtable-api/src/main/java/org/apache/xtable/model/sync/SyncResult.java
- xtable-api/src/main/java/org/apache/xtable/model/sync/SyncStatusCode.java
- xtable-api/src/main/java/org/apache/xtable/spi/extractor/CatalogConversionSource.java
- xtable-api/src/main/java/org/apache/xtable/spi/extractor/ConversionSource.java
- xtable-api/src/main/java/org/apache/xtable/spi/extractor/ExtractFromSource.java
- xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSync.java
- xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSyncClient.java
- xtable-api/src/main/java/org/apache/xtable/spi/sync/ConversionTarget.java
- xtable-api/src/main/java/org/apache/xtable/spi/sync/TableFormatSync.java
- xtable-api/src/test/java/org/apache/xtable/spi/sync/TestCatalogSync.java
- xtable-api/src/test/java/org/apache/xtable/spi/sync/TestTableFormatSync.java
- xtable-core/src/main/java/org/apache/xtable/conversion/ConversionController.java
- xtable-hudi-support/xtable-hudi-support-extensions/src/main/java/org/apache/xtable/hudi/sync/XTableSyncTool.java
Refactoring classes for SyncStatusCode and ErrorDetails into separate classes for the PolicySync interfaces and methods. 
https://github.com/apache/incubator-xtable/pull/644/files 
- *Refactor classes for SyncStatusCode and ErrorDetails*
- *Introduce maturity level for xtable-api module*
*(example:)*
- *xtable-api/src/test/java/org/apache/xtable/spi/sync/TestCatalogSync.java*
- *xtable-api/src/test/java/org/apache/xtable/spi/sync/TestTableFormatSync.java*
> [678] Introduce maturity-level in xtable-api and Refactor SyncStatusCode into separate class

- .asf.yaml
Other incubating projects have squash and merge enabled, trying it for XTable as well. 
https://github.com/apache/polaris/blob/main/.asf.yaml#L33 
- *Enable squash and merge in .asf.yaml for xtable*
> Enable squash and merge in .asf.yaml for xtable

- xtable-aws/pom.xml
- xtable-aws/src/main/resources/META-INF/LICENSE
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-antlr4-runtime
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-checker-qual
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-glassfish-java-servlet-jsp
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-javax-annotation-api
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-jol-core
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-paranamer
- xtable-aws/src/main/resources/META-INF/licenses/LICENSE-slf4j-api
Ran `mvn dependency:tree -pl xtable-aws` and included dependencies with other 3rd party licenses, all are still compatible with ASF guidelines. 
https://www.apache.org/legal/resolved.html#asf-3rd-party-license-policy 
- *Add LICENSE for xtable-aws module*
> [678] Add LICENSE for xtable-aws module

- xtable-hive-metastore/pom.xml
- xtable-hive-metastore/src/main/resources/META-INF/LICENSE
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-antlr4-runtime
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-checker-qual
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-glasshfish-javax-servlet
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-javax-annotation-api
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-javolution
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-jersey-core
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-jol-core
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-jruby-jcodings
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-jruby-joni
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-leveldbjni
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-paranamer
- xtable-hive-metastore/src/main/resources/META-INF/licenses/LICENSE-slf4j-api
Ran `mvn dependency:tree -pl xtable-hive-metastore` and included dependencies with other 3rd party licenses, all are still compatible with ASF guidelines.
https://www.apache.org/legal/resolved.html#asf-3rd-party-license-policy
- *Add LICENSE for xtable-hive-metastore module*
> [678] Add LICENSE for xtable-hive-metastore module

- xtable-api/src/main/java/org/apache/xtable/spi/sync/CatalogSync.java
- xtable-aws/src/main/java/org/apache/xtable/glue/GlueSchemaExtractor.java
- xtable-aws/src/test/java/org/apache/xtable/glue/GlueCatalogSyncTestBase.java
- xtable-aws/src/test/java/org/apache/xtable/glue/TestGlueSchemaExtractor.java
Glue does not support partition column having any parameters when registering a table, otherwise would result in 
`Caused by: software.amazon.awssdk.services.glue.model.InvalidInputException: Parameters not supported for partition columns`, so not setting parameters for partition columns
- *Fixed JSON parsing error when persisting state*
- *Added unit tests for schema evolution*
- Unit tests
> Remove parameters from Glue partition columns

- .gitignore
- spec/Makefile
- spec/README.md
- spec/requirements.txt
- spec/rest-service-open-api.yaml
* This pr add a new  open api `spec` module for the XTable REST Service(for handling metadata conversions remotely), see RFC for more details https://github.com/apache/incubator-xtable/pull/702
* added spec yaml file
* added open api spec linter
* Added MakeFile for running `make lint` to validate the spec is not invalid.
* added README
Ran the Makefile
```
make install
make lint
make clean
```
> Add open api REST spec for XTable Service

- xtable-core/src/test/java/org/apache/xtable/hudi/TestHudiInstantUtils.java
This pull request improves both the tests in `TestHudiInstantUtils` by refactoring them into parameterised unit tests and also adding more test cases to enhance testing logic. 
Elaboration: 
* The same method calls (parseFromInstantTime & convertInstantToCommit) are repeated with different inputs, making the test harder to maintain and extend.
* When a test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
* Adding new test cases requires copying and pasting another Assertions.assertEquals(...) statement instead of simply adding new data.
- *Parameterised tests: `testParseCommitTimeToInstant` & `testInstantToCommit`*
- *Added more test cases as value sets to above parameterised tests*
Below are the before and after unit test run …
> Improved all tests in TestHudiInstantUtils by parameterising and adding more test cases

- xtable-service/pom.xml
- xtable-service/src/test/java/org/apache/xtable/service/ITConversionService.java
- xtable-service/src/test/resources/application.properties
This pr aims to add integration tests which test the XTable REST Service for combinations of all table formats, for both partitioned and unpartitioned tables.
* Before we land this pr we will need to land the following pr: https://github.com/apache/incubator-xtable/pull/714 which has some bug fixes for the service.
Adds an IT Test for conversion service.
Ran the IT test locally which passes (see screenshot)
> Add intial IT for XTable REST Service
